name: Playwright Parity Matrix

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  parity:
    name: Parity Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Playwright export
        run: pnpm run docs:export-png:ci

      - name: Compare parity
        run: node scripts/compare-parity.mjs || true

      - name: Upload parity report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-parity-report
          path: reports/
