name: lighthouse

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build (prod)
        run: npm run build:prod

      - name: Run Lighthouse CI
        run: npx @lhci/cli@0.13.x autorun --config=./lighthouserc.json

      - name: Upload Lighthouse reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: .lighthouseci/*
